### ISSUE TITLE
systemd-git should not replace systemd

### ISSUE THREAD

**Issue by axionl** [yurikoles-aur/systemd-git#2]
the `replace` should use to the packages which renamed, `conflicts` is enough.

Issue: https://github.com/archlinuxcn/repo/issues/896

Source: https://github.com/yurikoles-aur/systemd-git/blob/66c19950f0097b01d3d3ca5cf2f00dd67d9a9972/PKGBUILD#L126

**Comment by yurikoles** [comment]
Fixed long time ago in cd3bcfeb957d63a2c1f6ec46ac0b56ea74ff0309
