### ISSUE TITLE
Package fails to install

### ISSUE THREAD

**Issue by ignapk** [yurikoles-aur/systemd-git#3]
Commit in upstream that introduced the problem: https://github.com/systemd/systemd/commit/6589a56972d9afe9d860889f11cb9c8e6cb8a60c

Error log:
rm: cannot remove '/home/ignacy/.cache/yay/systemd-git/pkg/systemd-git/usr/bin/runlevel': No such file or directory
rm: cannot remove '/home/ignacy/.cache/yay/systemd-git/pkg/systemd-git/usr/bin/telinit': No such file or directory

Fixed by changing PKGBUILD not to remove runlevel and telinit which are already missing

**Comment by yurikoles** [comment]
FIxed long time ago.
